# CI which executes the unit tests and uploads the report to Coveralls
name: CI

on:
  push:
    branches: [ master, test ]

jobs:

  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      uses: CultureHQ/actions-yarn@v1.0.1
      with:
        args: install

    - name: Execute Tests
      uses: CultureHQ/actions-yarn@v1.0.1
      with:
        args: test

    - name: Send to Coveralls
      uses: coverallsapp/github-action@v1.1.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
